# Generated by Django 3.0.8 on 2020-07-15 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskid', models.AutoField(primary_key=True, serialize=False)),
                ('taskname', models.CharField(max_length=50)),
                ('aboutoftask', models.CharField(max_length=100)),
                ('periodofexecution', models.DateField()),
                ('dateofcompletion', models.DateField(blank=True, null=True)),
                ('taskcomplexity', models.SmallIntegerField()),
                ('timetocompletethetask', models.SmallIntegerField()),
                ('taskstatus', models.CharField(max_length=20)),
                ('natureofthetask', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Useraccount',
            fields=[
                ('login', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('accountstatus', models.BooleanField()),
                ('datetimeauthorized', models.DateTimeField()),
            ],
            options={
                'db_table': 'useraccount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('login', models.OneToOneField(db_column='login', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='personalarea.Useraccount')),
                ('lastname', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('login', models.OneToOneField(db_column='login', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='personalarea.Useraccount')),
                ('lastname', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30)),
                ('grade', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'performer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Listofcoefficient',
            fields=[
                ('manager', models.OneToOneField(db_column='manager', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='personalarea.Manager')),
                ('minimumwagegm', models.IntegerField()),
                ('timetocompletethetaskti', models.SmallIntegerField()),
                ('coefficientofcosttimetc', models.SmallIntegerField()),
                ('taskcomplexitydi', models.SmallIntegerField()),
                ('coefficientoftaskcomplexityde', models.SmallIntegerField()),
                ('coefficientofnatureofworkci', models.FloatField()),
                ('forconvertedintocashtb', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'listofcoefficient',
                'managed': False,
            },
        ),
    ]
