# Generated by Django 3.0.8 on 2020-07-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Useraccount',
            fields=[
                ('login', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('accountstatus', models.BooleanField()),
                ('datetimeauthorized', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'useraccount',
                'managed': False,
            },
        ),
    ]
